# Generated by Django 2.0 on 2018-01-08 07:06

import betweak_django_cities.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betweak_django_cities', '0010_adjust_unique_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=betweak_django_cities.models.SET_NULL_OR_CASCADE, related_name='betweak_django_cities', to=settings.CITIES_COUNTRY_MODEL),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=betweak_django_cities.models.SET_NULL_OR_CASCADE, related_name='betweak_django_cities', to='betweak_django_cities.Region'),
        ),
        migrations.AlterField(
            model_name='city',
            name='subregion',
            field=models.ForeignKey(blank=True, null=True, on_delete=betweak_django_cities.models.SET_NULL_OR_CASCADE, related_name='betweak_django_cities', to='betweak_django_cities.Subregion'),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(null=True, on_delete=betweak_django_cities.models.SET_NULL_OR_CASCADE, related_name='countries', to=settings.CITIES_CONTINENT_MODEL),
        ),
        migrations.AlterField(
            model_name='district',
            name='city',
            field=models.ForeignKey(on_delete=betweak_django_cities.models.SET_NULL_OR_CASCADE, related_name='districts', to=settings.CITIES_CITY_MODEL),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=betweak_django_cities.models.SET_NULL_OR_CASCADE, related_name='postal_codes', to=settings.CITIES_CITY_MODEL),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=betweak_django_cities.models.SET_NULL_OR_CASCADE, related_name='postal_codes', to='betweak_django_cities.District'),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=betweak_django_cities.models.SET_NULL_OR_CASCADE, related_name='postal_codes', to='betweak_django_cities.Region'),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='subregion',
            field=models.ForeignKey(blank=True, null=True, on_delete=betweak_django_cities.models.SET_NULL_OR_CASCADE, related_name='postal_codes', to='betweak_django_cities.Subregion'),
        ),
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.ForeignKey(on_delete=betweak_django_cities.models.SET_NULL_OR_CASCADE, related_name='regions', to=settings.CITIES_COUNTRY_MODEL),
        ),
        migrations.AlterField(
            model_name='subregion',
            name='region',
            field=models.ForeignKey(on_delete=betweak_django_cities.models.SET_NULL_OR_CASCADE, related_name='subregions', to='betweak_django_cities.Region'),
        ),
    ]
